fix SCU installation scripts
mbta/on_prem_deploy pull request #81
Opened 2024-09-27 18:43 UTC by panentheos

Fixes a few issues that came up during testing of the SCU install process.

* Makes the ISO build script fail loudly on errors
* Allows specifying git branches with slashes
* Adds users to the `admin` group for sudo privileges
* Uses the `classic` flag to install the SSM agent
* Installs the SSH server on SCUs

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208422519448697

2024-09-27 18:45 UTC, panentheos commented on linux/group_vars/scu/users.yml
> +    groups: [admin, users]
Please double check this change. These groups were specified as `admin` originally, but changed to `sudo` at some point. However, with the way sudo privileges are being granted, I think `admin` is correct.

2024-10-02 14:12 UTC, ianwestcott commented on linux/group_vars/scu/users.yml
> +    groups: [admin, users]
That change happened here: https://github.com/mbta/on_prem_deploy/pull/49 I don't remember exactly why, but I vaguely recall the `admin` group not existing in some images?

2024-10-02 14:15 UTC, ianwestcott commented on linux/group_vars/scu/users.yml
> +    groups: [admin, users]
Ah, yeah – in [this comment](https://github.com/mbta/on_prem_deploy/pull/49#issuecomment-1960378145) I noted that I tripped over the `admin` group not existing in a local test environment. @panentheos are you sure it exists on the SCU image you're building?

2024-10-02 17:33 UTC, Warren-Johnson-TID requested changes
@panentheos  Ian added a comment about the sudo vs admin group.  Can you check it out?

2024-10-03 13:24 UTC, panentheos commented on linux/group_vars/scu/users.yml
> +    groups: [admin, users]
The `admin` group gets created if it doesn't exist via [this task](https://github.com/mbta/on_prem_deploy/blob/777e358d08d487342dc994f7a7fcbab7398de644/linux/roles/users/tasks/users.yml#L7). Maybe that was added later? Anyway, in my local test this seemed to work, I just wanted to make sure there wasn't some other reason not to do this.

2024-10-03 13:48 UTC, Warren-Johnson-TID approved these changes

2024-10-03 13:48 UTC, Warren-Johnson-TID commented on linux/group_vars/scu/users.yml
> +    groups: [admin, users]
Looks good. Thanks guys.

2024-10-03 13:49 UTC, Warren-Johnson-TID approved these changes
Looks good.

2024-10-03 13:50 UTC, merged